language: ruby
sudo: required
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

install:
  - sudo apt-get update -qq
  - sudo apt-get install libpcap-dev -qq
  - bundle install --path vendor/bundle --jobs=3 --retry=3
before_script:
  - openssl version
  - ruby -ropenssl -e 'puts OpenSSL::VERSION'
script:
  - bundle exec rake
  - rvmsudo bundle exec rake spec:sudo
