language: ruby
os: linux
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
install:
  - sudo apt-get update -qq
  - sudo apt-get install libpcap-dev -qq
  - gem install bundler
  - bundle config set path 'vendor/bundle'
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec rake
  - rvmsudo bundle exec rake spec:sudo
